# Generated by Django 4.2.7 on 2025-07-21 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the API configuration', max_length=255)),
                ('swagger_url', models.URLField(help_text='Swagger/OpenAPI specification URL')),
                ('api_base_url', models.URLField(help_text='Base URL of the REST API')),
                ('description', models.TextField(blank=True, help_text='Description of the REST API service')),
                ('auth_type', models.CharField(choices=[('none', 'No Authentication'), ('api_key', 'API Key'), ('bearer_token', 'Bearer Token'), ('basic_auth', 'Basic Authentication'), ('oauth2', 'OAuth2')], default='none', max_length=20)),
                ('auth_config', models.JSONField(default=dict, help_text='Authentication configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Configuration',
                'verbose_name_plural': 'API Configurations',
                'db_table': 'core_api_configuration',
            },
        ),
        migrations.CreateModel(
            name='GeneratedYAMLFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('tools_count', models.IntegerField(default=0)),
                ('generation_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yaml_files', to='core.apiconfiguration')),
            ],
            options={
                'verbose_name': 'Generated YAML File',
                'verbose_name_plural': 'Generated YAML Files',
                'db_table': 'core_generated_yaml_file',
            },
        ),
        migrations.CreateModel(
            name='MCPServerInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=255)),
                ('server_port', models.IntegerField(blank=True, null=True)),
                ('is_running', models.BooleanField(default=False)),
                ('server_config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('yaml_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_server', to='core.generatedyamlfile')),
            ],
            options={
                'verbose_name': 'MCP Server Instance',
                'verbose_name_plural': 'MCP Server Instances',
                'db_table': 'core_mcp_server_instance',
            },
        ),
        migrations.CreateModel(
            name='APIEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=10)),
                ('operation_id', models.CharField(blank=True, max_length=255)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('enhanced_description', models.TextField(blank=True)),
                ('enhanced_summary', models.CharField(blank=True, max_length=500)),
                ('parameters', models.JSONField(default=list)),
                ('responses', models.JSONField(default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('tool_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('yaml_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='core.generatedyamlfile')),
            ],
            options={
                'verbose_name': 'API Endpoint',
                'verbose_name_plural': 'API Endpoints',
                'db_table': 'core_api_endpoint',
                'unique_together': {('yaml_file', 'path', 'method')},
            },
        ),
        migrations.CreateModel(
            name='ParameterEnhancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=255)),
                ('original_description', models.TextField(blank=True)),
                ('enhanced_description', models.TextField()),
                ('parameter_type', models.CharField(blank=True, max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_enhancements', to='core.apiendpoint')),
            ],
            options={
                'verbose_name': 'Parameter Enhancement',
                'verbose_name_plural': 'Parameter Enhancements',
                'db_table': 'core_parameter_enhancement',
                'unique_together': {('endpoint', 'parameter_name')},
            },
        ),
    ]
