# Generated by Django 4.2.7 on 2025-07-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedyamlfile',
            old_name='api_config',
            new_name='api_configuration',
        ),
        migrations.AddField(
            model_name='generatedyamlfile',
            name='yaml_content',
            field=models.TextField(blank=True, default='', help_text='Generated YAML content'),
        ),
        migrations.AlterField(
            model_name='generatedyamlfile',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='generatedyamlfile',
            name='file_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
